### ISSUE TITLE
Buttons don't fit YouTube's UI

### ISSUE THREAD

**Issue by angrybacon** [darajava/youtube-smooth#20]

**Comment by darajava** [comment]
What would you suggest?

**Comment by angrybacon** [comment]
``` scss
button.add-playlist {
  background-color: #F8F8F8;
  border-color: #D3D3D3;
  box-shadow: none;
  color: #333333;
  margin-right: 1px;
  padding: 3px 10px;
  text-shadow: none;

  &:hover {
    border-color: #C6C6C6;
    background: #F0F0F0;
    box-shadow: 0 1px 0 rgba(0, 0, 0, .1);
  }
}
```

You might want to try to have access to Material icons. That is to replace the icons for "Move up" and "Move down" respectively.

![screen shot 2016-06-03 at 15 16 47](https://cloud.githubusercontent.com/assets/5608624/15779739/51d154f6-299e-11e6-909b-9d2cad224d33.png)
